version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "repro-423"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1rttuy5xrd93z"
s3_prefix = "repro-423"
region = "eu-north-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
